### ISSUE TITLE
Update to selenium-jupiter v5.0.0 fails

### ISSUE THREAD

**Issue by javiertuya** [giis-uniovi/retorch-st-fullteaching#36]
See #35

**Comment by augustocristian** [comment]
Currently, I'm in the process of updating the Java version to 21, the latest stable release. I'm also analyzing the slave version to ensure it aligns with the new versions used on GitHub @javiertuya .

**Comment by javiertuya** [comment]
@augustocristian Java 21 is not necessary, the general rule of thumb is: use the minimum LTS that is compatible

**Comment by augustocristian** [comment]
According to the [Changelog](https://github.com/bonigarcia/selenium-jupiter/blob/master/CHANGELOG.md), the project has been updated to use Java 17, ensuring complete alignment and the utilization of the Selenide dependency. In the documentation, it states: 'Selenium-Jupiter should be employed as a Java dependency (requiring JDK 17 or higher). '". "The agent is now on Alpine 17, ensuring alignment. @javiertuya

**Comment by javiertuya** [comment]
@augustocristian As I told before (somewere), NEVER add commits to dependabot updates, because this will prevent to be included in combined updates (as they will cherry pick the latest commit only).

According to the changelog, the requirement is java 17, not java 21:
![image](https://github.com/giis-uniovi/retorch-st-fullteaching/assets/10879637/84e8c364-4f7a-4162-a7c9-6813e8448e5d)

I have deleted the branch and recreated the PR
